### ISSUE TITLE
Telugu version of the site isn't properly visible

### ISSUE THREAD

**Issue by rish07** [rajchandra3/fight-corona#14]
The Telugu version of the site is not getting rendered properly.
![Screenshot from 2020-04-02 02-09-23](https://user-images.githubusercontent.com/49035175/78184603-5e511300-7487-11ea-8e38-71e5b3b2f50b.png)

**Comment by rajchandra3** [comment]
@rish07 can you mention the details about the device.

OS and it's version:
Browser used and it's version:

**Comment by rish07** [comment]
OS and its version: PopOS 19.10
Browser used and it's version: Google Chrome, Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by rajchandra3** [comment]
[https://support.microsoft.com/en-us/help/3083806/why-does-some-text-display-with-square-boxes-in-some-apps-on-windows-1](https://support.microsoft.com/en-us/help/3083806/why-does-some-text-display-with-square-boxes-in-some-apps-on-windows-1)  
Looks like this may be the issue, whether or not this is the issue? @rish07

**Comment by rish07** [comment]
Although I'm using PopOS, the problem seems to be similar. Maybe my system doesn't have the font installed. I'll check.

**Comment by rajchandra3** [comment]
Closing this for now, as it is a problem specific to a system.
