### ISSUE TITLE
non-responsive cards

### ISSUE THREAD

**Issue by noob-master147** [rajchandra3/fight-corona#15]
### These Cards are not responsive and no information is conveyed

![image](https://user-images.githubusercontent.com/43108912/78230537-15cd4000-74ef-11ea-925a-77d11ad57326.png)

**Comment by rajchandra3** [comment]
Looks like the API broke, I will fix this as soon as possible.

We are working on this.

**Comment by rajchandra3** [comment]
Fixed it
