### ISSUE TITLE
Add district wise data for all the states

### ISSUE THREAD

**Issue by rajchandra3** [rajchandra3/fight-corona#6]
I will leave the api in the comments below soon.

**Comment by noob-master147** [comment]
@rajchandra3 API please!!!

**Comment by rajchandra3** [comment]
https://api.covid19india.org/v2/state_district_wise.json @noob-master147

**Comment by noob-master147** [comment]
Thanks, @rajchandra3

**Comment by rajchandra3** [comment]
@noob-master147 join us on slack [https://corona-go-app.slack.com/](https://corona-go-app.slack.com/)

**Comment by rajchandra3** [comment]
Done https://github.com/rajchandra3/fight-corona/pull/19
